spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lesson1
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  gson:
    pretty-printing: true